# Generated by Django 4.1 on 2022-09-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0006_watchlist_avg_rating_watchlist_number_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='avg_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='no_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
