# Generated by Django 4.1 on 2022-09-16 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0007_review_avg_ratings_review_no_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='avg_ratings',
            new_name='avg_rating',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='no_ratings',
            new_name='number_ratings',
        ),
    ]
